image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: cezelot.site
tasks:
- package: |
    cd $site
    tar -cvz --exclude='./.*' --exclude='README.md' . > ../site.tar.gz
- upload: |
    hut pages publish -d sh.cezelot.me site.tar.gz
